// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addChatGroupMember = `-- name: AddChatGroupMember :exec
INSERT INTO chat_group_members (user_id, chat_group_id)
VALUES ($1, $2)
ON CONFLICT (user_id, chat_group_id) DO NOTHING
`

type AddChatGroupMemberParams struct {
	UserID      uuid.UUID
	ChatGroupID uuid.UUID
}

func (q *Queries) AddChatGroupMember(ctx context.Context, arg AddChatGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, addChatGroupMember, arg.UserID, arg.ChatGroupID)
	return err
}

const createChatGroupWithCreator = `-- name: CreateChatGroupWithCreator :one
WITH new_group AS (
    INSERT INTO chat_groups (name, created_by)
    VALUES ($1, $2)
    RETURNING id, name, created_at, created_by
), added_creator AS (
    INSERT INTO chat_group_members (user_id, chat_group_id)
    SELECT created_by, id
    FROM new_group
    RETURNING chat_group_id
)
SELECT id, name, created_at, created_by
FROM new_group
`

type CreateChatGroupWithCreatorParams struct {
	Name      string
	CreatedBy uuid.UUID
}

type CreateChatGroupWithCreatorRow struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	CreatedBy uuid.UUID
}

func (q *Queries) CreateChatGroupWithCreator(ctx context.Context, arg CreateChatGroupWithCreatorParams) (CreateChatGroupWithCreatorRow, error) {
	row := q.db.QueryRowContext(ctx, createChatGroupWithCreator, arg.Name, arg.CreatedBy)
	var i CreateChatGroupWithCreatorRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}
