// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const chatGroupExists = `-- name: ChatGroupExists :one
SELECT EXISTS (
    SELECT 1 FROM chat_groups WHERE id = $1
) AS exists
`

func (q *Queries) ChatGroupExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, chatGroupExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    sender_id,
    receiver_id,
    body
) VALUES (
    $1, $2, $3
)
RETURNING id, created_at, sender_id, receiver_id, body
`

type CreateMessageParams struct {
	SenderID   uuid.UUID
	ReceiverID uuid.UUID
	Body       string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage, arg.SenderID, arg.ReceiverID, arg.Body)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.SenderID,
		&i.ReceiverID,
		&i.Body,
	)
	return i, err
}

const getConversationsByUserID = `-- name: GetConversationsByUserID :many
WITH recent AS (
    SELECT
        CASE
            WHEN groups.id IS NOT NULL THEN messages.receiver_id
            WHEN messages.sender_id = $1 THEN messages.receiver_id
            ELSE messages.sender_id
        END AS other_id,
        MAX(messages.created_at) AS latest
    FROM messages
    LEFT JOIN chat_groups AS groups ON groups.id = messages.receiver_id
    WHERE (
        groups.id IS NOT NULL
        AND messages.receiver_id IN (
            SELECT chat_group_id
            FROM chat_group_members
            WHERE user_id = $1
        )
    ) OR (
        groups.id IS NULL
        AND (messages.sender_id = $1 OR messages.receiver_id = $1)
    )
    GROUP BY other_id
)
SELECT u.id, u.name, r.latest
FROM recent r
JOIN users u ON r.other_id = u.id

UNION ALL

SELECT c.id, c.name, r.latest
FROM chat_group_members AS members
JOIN chat_groups AS c ON c.id = members.chat_group_id
LEFT JOIN recent AS r ON r.other_id = c.id
WHERE members.user_id = $1

ORDER BY latest DESC NULLS LAST
`

type GetConversationsByUserIDRow struct {
	ID     uuid.UUID
	Name   string
	Latest interface{}
}

func (q *Queries) GetConversationsByUserID(ctx context.Context, senderID uuid.UUID) ([]GetConversationsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getConversationsByUserID, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationsByUserIDRow
	for rows.Next() {
		var i GetConversationsByUserIDRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Latest); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDuelMessages = `-- name: GetDuelMessages :many

SELECT id, created_at, sender_id, receiver_id, body 
FROM messages 
WHERE (receiver_id = $1 AND sender_id = $2) OR (receiver_id = $2 AND sender_id = $1)
ORDER BY created_at DESC
`

type GetDuelMessagesParams struct {
	ReceiverID uuid.UUID
	SenderID   uuid.UUID
}

func (q *Queries) GetDuelMessages(ctx context.Context, arg GetDuelMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getDuelMessages, arg.ReceiverID, arg.SenderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.SenderID,
			&i.ReceiverID,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupMemberIDs = `-- name: GetGroupMemberIDs :many
SELECT user_id
FROM chat_group_members
WHERE chat_group_id = $1
`

func (q *Queries) GetGroupMemberIDs(ctx context.Context, chatGroupID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getGroupMemberIDs, chatGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupMessages = `-- name: GetGroupMessages :many
SELECT id, created_at, sender_id, receiver_id, body
FROM messages 
WHERE receiver_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetGroupMessages(ctx context.Context, receiverID uuid.UUID) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getGroupMessages, receiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.SenderID,
			&i.ReceiverID,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isGroupMember = `-- name: IsGroupMember :one
SELECT EXISTS (
    SELECT 1
    FROM chat_group_members
    WHERE chat_group_id = $1
      AND user_id = $2
) AS exists
`

type IsGroupMemberParams struct {
	ChatGroupID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) IsGroupMember(ctx context.Context, arg IsGroupMemberParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isGroupMember, arg.ChatGroupID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
