// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const chatGroupExists = `-- name: ChatGroupExists :one
SELECT EXISTS (
    SELECT 1 FROM chat_groups WHERE id = $1
) AS exists
`

func (q *Queries) ChatGroupExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, chatGroupExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    sender_id,
    receiver_id,
    body
) VALUES (
    $1, $2, $3
)
RETURNING id, created_at, sender_id, receiver_id, body
`

type CreateMessageParams struct {
	SenderID   uuid.UUID
	ReceiverID uuid.UUID
	Body       string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage, arg.SenderID, arg.ReceiverID, arg.Body)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.SenderID,
		&i.ReceiverID,
		&i.Body,
	)
	return i, err
}

const getConversationsByUserID = `-- name: GetConversationsByUserID :many
WITH recent AS (
    SELECT receiver_id, MAX(created_at) AS latest
    FROM messages
    WHERE sender_id = $1
    GROUP BY receiver_id
)
SELECT u.name, r.latest
FROM recent r , users u 
WHERE r.receiver_id = u.id 

UNION ALL

SELECT c.name, r.latest
FROM recent r, chat_groups c
WHERE r.receiver_id = c.id 

ORDER BY latest DESC
`

type GetConversationsByUserIDRow struct {
	Name   string
	Latest interface{}
}

func (q *Queries) GetConversationsByUserID(ctx context.Context, senderID uuid.UUID) ([]GetConversationsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getConversationsByUserID, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationsByUserIDRow
	for rows.Next() {
		var i GetConversationsByUserIDRow
		if err := rows.Scan(&i.Name, &i.Latest); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDuelMessages = `-- name: GetDuelMessages :many

SELECT id, created_at, sender_id, receiver_id, body 
FROM messages 
WHERE (receiver_id = $1 AND sender_id = $2) OR (receiver_id = $2 AND sender_id = $1)
ORDER BY created_at DESC
`

type GetDuelMessagesParams struct {
	ReceiverID uuid.UUID
	SenderID   uuid.UUID
}

func (q *Queries) GetDuelMessages(ctx context.Context, arg GetDuelMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getDuelMessages, arg.ReceiverID, arg.SenderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.SenderID,
			&i.ReceiverID,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupMessages = `-- name: GetGroupMessages :many
SELECT id, created_at, sender_id, receiver_id, body
FROM messages 
WHERE receiver_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetGroupMessages(ctx context.Context, receiverID uuid.UUID) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getGroupMessages, receiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.SenderID,
			&i.ReceiverID,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isGroupMember = `-- name: IsGroupMember :one
SELECT EXISTS (
    SELECT 1
    FROM chat_group_members
    WHERE chat_group_id = $1
      AND user_id = $2
) AS exists
`

type IsGroupMemberParams struct {
	ChatGroupID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) IsGroupMember(ctx context.Context, arg IsGroupMemberParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isGroupMember, arg.ChatGroupID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
