// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ChatGroup struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	CreatedBy uuid.UUID
}

type ChatGroupMember struct {
	UserID      uuid.UUID
	ChatGroupID uuid.UUID
	JoinedAt    time.Time
}

type Message struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	SenderID   uuid.UUID
	ReceiverID uuid.UUID
	Body       string
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
	UsedAt    sql.NullTime
	FamilyID  uuid.UUID
}

type User struct {
	ID       uuid.UUID
	Name     string
	Password string
}
