// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Conversation struct {
	ID   uuid.UUID
	Name string
}

type Invitation struct {
	ID             uuid.UUID
	Status         string
	ConversationID uuid.UUID
	SenderID       uuid.UUID
	ReceiverID     uuid.UUID
}

type Member struct {
	UserID         uuid.UUID
	ConversationID uuid.UUID
}

type Message struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UserID         uuid.UUID
	ConversationID uuid.UUID
	Body           string
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
	UsedAt    sql.NullTime
	FamilyID  uuid.UUID
}

type User struct {
	ID       uuid.UUID
	Name     string
	Password string
}
