// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    user_id,
    token,
    expires_at,
    family_id
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, user_id, token, expires_at, used_at, family_id
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
	FamilyID  uuid.UUID
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
		arg.FamilyID,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.FamilyID,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token, expires_at, used_at, family_id
FROM refresh_tokens
WHERE token = $1
LIMIT 1
`

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.FamilyID,
	)
	return i, err
}

const revokeRefreshTokensByFamilyID = `-- name: RevokeRefreshTokensByFamilyID :exec
DELETE FROM refresh_tokens
WHERE family_id = $1
`

func (q *Queries) RevokeRefreshTokensByFamilyID(ctx context.Context, familyID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshTokensByFamilyID, familyID)
	return err
}
