// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (password, name)
VALUES ($1, $2)
RETURNING id, name, password
`

type CreateUserParams struct {
	Password string
	Name     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Password, arg.Name)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Password)
	return i, err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS(
    SELECT 1 FROM users WHERE name = $1
) AS exists
`

func (q *Queries) UserExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
