// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: add_chirps.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createChirps = `-- name: CreateChirps :one
INSERT INTO chirps (created_at, updated_at, body, user_id)
VALUES (
    now(), now(), $1, $2
)
RETURNING id, created_at, updated_at, user_id, body
`

type CreateChirpsParams struct {
	Body   string
	UserID uuid.UUID
}

func (q *Queries) CreateChirps(ctx context.Context, arg CreateChirpsParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, createChirps, arg.Body, arg.UserID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Body,
	)
	return i, err
}
